kind: pipeline
type: ssh
name: default

server:
  host:
    from_secret: host
  user:
    from_secret: username
  ssh_key:
    from_secret: key

steps:
  - name: build
    commands:
      - sudo docker compose build

  - name: deploy
    commands:
      - sudo rm -rf application
      - sudo git clone https://github.com/CHunYenc/crypto-price-scheduler.git application
      - sudo cd application
      - sudo echo SECRET_KEY = $${SECRET_KEY} > backend/.env
      - sudo echo REDIS_HOST = $${REDIS_HOST} >> backend/.env
      - sudo echo REDIS_PORT = $${REDIS_PORT} >> backend/.env
      - sudo docker compose rm -f
      - sudo docker image prune -a
      - sudo docker compose up -d

depends_on:
  - ready