kind: pipline
type: docker
name: ready

steps:
  - name: setup
    image: python:3.7-slim
    commands:
      - pip install --upgrade pip
      - pip install -r backend/requirements.txt
  
  # - name: test
    # image: python

---
kind: pipeline
type: ssh
name: production

server:
  host:
    from_secret: host
  user:
    from_secret: username
  ssh_key:
    from_secret: key

steps:
  - name: deploy
    commands:
      - sudo su
      - rm -rf application
      - git clone https://github.com/CHunYenc/crypto-price-scheduler.git application
      - cd application
      - echo SECRET_KEY = $${SECRET_KEY} > backend/.env
      - echo REDIS_HOST = $${REDIS_HOST} >> backend/.env
      - echo REDIS_PORT = $${REDIS_PORT} >> backend/.env
      - docker compose rm -f
      - docker image prune -a
      - docker compose up -d