"""empty message

Revision ID: 5fe203b16afd
Revises: f52b87582542
Create Date: 2022-01-30 22:08:48.674963

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5fe203b16afd'
down_revision = 'f52b87582542'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('crypto_price')
    op.create_unique_constraint(None, 'focus_symbol', ['symbol'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'focus_symbol', type_='unique')
    op.create_table('crypto_price',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('exchange', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('symbol', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('price', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('create_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='crypto_price_pkey')
    )
    # ### end Alembic commands ###
