"""empty message

Revision ID: c4ece7ee7a77
Revises: ef11ed8a5ece
Create Date: 2022-02-02 00:10:09.995450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4ece7ee7a77'
down_revision = 'ef11ed8a5ece'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('focus_symbol_symbol_A_symbol_B_key', 'focus_symbol', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('focus_symbol_symbol_A_symbol_B_key', 'focus_symbol', ['symbol_A', 'symbol_B'])
    # ### end Alembic commands ###
