"""empty message

Revision ID: e05885cdc468
Revises: 5fe203b16afd
Create Date: 2022-02-01 23:47:41.678289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e05885cdc468'
down_revision = '5fe203b16afd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('focus_symbol', sa.Column('symbol_A', sa.String(length=10), nullable=False))
    op.add_column('focus_symbol', sa.Column('symbol_B', sa.String(length=10), nullable=False))
    op.drop_constraint('focus_symbol_symbol_key', 'focus_symbol', type_='unique')
    op.create_unique_constraint(None, 'focus_symbol', ['exchange', 'symbol_A', 'symbol_B'])
    op.create_unique_constraint(None, 'focus_symbol', ['symbol_A'])
    op.create_unique_constraint(None, 'focus_symbol', ['symbol_B'])
    op.drop_column('focus_symbol', 'symbol')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('focus_symbol', sa.Column('symbol', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'focus_symbol', type_='unique')
    op.drop_constraint(None, 'focus_symbol', type_='unique')
    op.drop_constraint(None, 'focus_symbol', type_='unique')
    op.create_unique_constraint('focus_symbol_symbol_key', 'focus_symbol', ['symbol'])
    op.drop_column('focus_symbol', 'symbol_B')
    op.drop_column('focus_symbol', 'symbol_A')
    # ### end Alembic commands ###
