"""empty message

Revision ID: fb6bff147f9e
Revises: e05885cdc468
Create Date: 2022-02-02 00:06:11.926814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb6bff147f9e'
down_revision = 'e05885cdc468'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'focus_symbol', ['symbol_A', 'symbol_B'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'focus_symbol', type_='unique')
    # ### end Alembic commands ###
